### ISSUE TITLE
could it support vue3?

### ISSUE THREAD

**Issue by jtdhyl** [gwenaelp/vue-diagrams#28]
Vue2 will cease maintenance on December 31, 2023

**Comment by gwenaelp** [comment]
Hello, I am currently working on a vue3 version :). It seems to work but I still need some work to be done. I'll try to publish it in a vue-3 branch soon

**Comment by jtdhyl** [comment]
> Hello, I am currently working on a vue3 version :). It seems to work but I still need some work to be done. I'll try to publish it in a vue-3 branch soon

thank you very much

**Comment by gwenaelp** [comment]
Hi :wave: 

Just to say that some work has been pushed to the Vue 3 branch!

It's not perfect yet, but you might be able to navigate most of the stories and to use the library.

Do not hesitate to provide feedback, and feel free to post a PR if you want to improve the library!

All the best!

**Comment by jtdhyl** [comment]
This has been a great help to me, you are the best

**Comment by gwenaelp** [comment]
Glad to hear that! 

I'm closing the issue =)
