### ISSUE TITLE
How can I hide remove button?

### ISSUE THREAD

**Issue by SoohyunFantasticJo** [gwenaelp/vue-diagrams#5]
Dear Gwenaelp,
This is SJ, an senior researcher in Korea.

I have a question about vue-diagreams.
How can I hide remove button?

https://github.com/gwenaelp/vue-diagrams/raw/master/images/example1.png

A node "Test3" does not have remove button in demo image as above. But the others have it.
I can't find source code for to hide it.

Thank you,
SJ.

**Comment by manjitp46** [comment]
Hi 
You can hide remove icon by setting deletable property of node to false.
Example:
    const node2 = diagramModel.addNode("test", 10, 300, 144, 80);
    const node2OutPort = node2.addOutPort("testOut");
    node2.addOutPort("testOut2");
    node2.color = "#00cc66";
    node2.deletable = false;
